const sampleListings = [
    {
      name: "Cozy Beachfront Cottage",
      description:
        "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1500,
      location: "Malibu",
      country: "United States",
      geometry: {
        type: "Point",
        coordinates: [-118.7798, 34.0259],
      },
      type: "Cottage",
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      checkin: "3:00 PM",
      features: ["WiFi", "Ocean View", "Private Beach"],
      checkout: "11:00 AM",
    },
    {
      name: "Modern Loft in Downtown",
      description:
        "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1200,
      location: "New York City",
      country: "United States",
      geometry: {
        type: "Point",
        coordinates: [-74.006, 40.7128],
      },
      type: "Loft",
      bedrooms: 1,
      bathrooms: 1,
      guests: 2,
      checkin: "4:00 PM",
      features: ["WiFi", "City View", "Elevator", "Air Conditioning"],
      checkout: "12:00 PM",
    },
    {
      name: "Mountain Retreat",
      description:
        "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 1000,
      location: "Aspen",
      country: "United States",
      geometry: {
        type: "Point",
        coordinates: [-106.8374, 39.1911],
      },
      type: "Cabin",
      bedrooms: 2,
      bathrooms: 1,
      guests: 5,
      checkin: "2:00 PM",
      features: ["Fireplace", "Mountain View", "WiFi", "Hiking Trails"],
      checkout: "10:00 AM",
    },
    {
      name: "Historic Villa in Tuscany",
      description:
        "Experience the charm of Tuscany in this beautifully restored villa. Explore the rolling hills and vineyards.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8aG90ZWxzfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 2500,
      location: "Florence",
      country: "Italy",
      geometry: {
        type: "Point",
        coordinates: [11.2558, 43.7696],
      },
      type: "Villa",
      bedrooms: 4,
      bathrooms: 3,
      guests: 8,
      checkin: "3:00 PM",
      features: ["Pool", "Wine Cellar", "Garden", "WiFi"],
      checkout: "11:00 AM",
    },
    {
      name: "Secluded Treehouse Getaway",
      description:
        "Live among the treetops in this unique treehouse retreat. A true nature lover's paradise.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 800,
      location: "Portland",
      country: "United States",
      geometry: {
        type: "Point",
        coordinates: [-122.6765, 45.5231],
      },
      type: "Treehouse",
      bedrooms: 1,
      bathrooms: 1,
      guests: 2,
      checkin: "1:00 PM",
      features: ["Forest View", "Deck", "WiFi", "Nature Trails"],
      checkout: "10:30 AM",
    },
    {
      name: "Beachfront Paradise",
      description:
        "Step out of your door onto the sandy beach. This beachfront condo offers the ultimate relaxation.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsc3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 2000,
      location: "Cancun",
      country: "Mexico",
      geometry: {
        type: "Point",
        coordinates: [-86.8475, 21.1619],
      },
      type: "Condo",
      bedrooms: 2,
      bathrooms: 2,
      guests: 6,
      checkin: "3:00 PM",
      features: ["Pool", "WiFi", "Beach Access", "Balcony"],
      checkout: "11:00 AM",
    },
    {
      name: "Rustic Cabin by the Lake",
      description:
        "Spend your days fishing and kayaking on the serene lake. This cozy cabin is perfect for outdoor enthusiasts.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 900,
      location: "Lake Tahoe",
      country: "United States",
      geometry: {
        type: "Point",
        coordinates: [-120.044, 39.0968],
      },
      type: "Cabin",
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      checkin: "2:30 PM",
      features: ["Lake View", "Kayaks", "Fireplace", "Fishing Gear"],
      checkout: "10:30 AM",
    },
    {
      name: "Luxury Penthouse with City Views",
      description:
        "Indulge in luxury living with panoramic city views from this stunning penthouse apartment.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1622396481328-9b1b78cdd9fd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 3500,
      location: "Los Angeles",
      country: "United States",
      geometry: {
        type: "Point",
        coordinates: [-118.2437, 34.0522],
      },
      type: "Penthouse",
      bedrooms: 3,
      bathrooms: 3,
      guests: 6,
      checkin: "4:00 PM",
      features: ["Rooftop Terrace", "WiFi", "City View", "Hot Tub"],
      checkout: "12:00 PM",
    },
    {
      name: "Ski-In/Ski-Out Chalet",
      description:
        "Hit the slopes right from your doorstep in this ski-in/ski-out chalet in the Swiss Alps.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1502784444187-359ac186c5bb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 3000,
      location: "Verbier",
      country: "Switzerland",
      geometry: {
        type: "Point",
        coordinates: [7.2261, 46.0961],
      },
      type: "Chalet",
      bedrooms: 4,
      bathrooms: 3,
      guests: 10,
      checkin: "3:00 PM",
      features: ["Ski-in/Ski-out", "Fireplace", "WiFi", "Sauna"],
      checkout: "11:00 AM",
    },
    {
      name: "Safari Lodge in the Serengeti",
      description:
        "Experience the thrill of the wild in a comfortable safari lodge. Witness the Great Migration up close.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mjl8fG1vdW50YWlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 4000,
      location: "Serengeti National Park",
      country: "Tanzania",
      geometry: {
        type: "Point",
        coordinates: [34.6857, -2.3333],
      },
      type: "Lodge",
      bedrooms: 5,
      bathrooms: 5,
      guests: 12,
      checkin: "2:00 PM",
      features: ["Safari Tours", "WiFi", "Wildlife View", "All-Inclusive Meals"],
      checkout: "10:00 AM",
    },
    {
      name: "Historic Canal House",
      description:
        "Stay in a piece of history in this beautifully preserved canal house in Amsterdam's iconic district.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Y2FtcGluZ3xlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1800,
      location: "Amsterdam",
      country: "Netherlands",
      geometry: {
        type: "Point",
        coordinates: [4.9041, 52.3676],
      },
      type: "Canal House",
      bedrooms: 3,
      bathrooms: 2,
      guests: 6,
      checkin: "3:00 PM",
      features: ["Canal View", "WiFi", "Historic Charm", "Bikes Included"],
      checkout: "11:00 AM",
    },
    {
      name: "Private Island Retreat",
      description:
        "Have an entire island to yourself for a truly exclusive and unforgettable vacation experience.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1618140052121-39fc6db33972?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bG9kZ2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 10000,
      location: "Fiji",
      country: "Fiji",
      geometry: {
        type: "Point",
        coordinates: [178.065, -17.7134],
      },
      type: "Private Island",
      bedrooms: 8,
      bathrooms: 8,
      guests: 16,
      checkin: "12:00 PM",
      features: ["Private Beach", "Pool", "Chef", "Boat Included"],
      checkout: "10:00 AM",
    },
    {
      name: "Charming Cottage in the Cotswolds",
      description:
        "Escape to the picturesque Cotswolds in this quaint and charming cottage with a thatched roof.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1602088113235-229c19758e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8YmVhY2glMjB2YWNhdGlvbnxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1200,
      location: "Cotswolds",
      country: "United Kingdom",
      geometry: {
        type: "Point",
        coordinates: [-1.785, 51.833],
      },
      type: "Cottage",
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      checkin: "3:00 PM",
      features: ["Garden", "WiFi", "Fireplace", "Thatched Roof"],
      checkout: "11:00 AM",
    },
    {
      name: "Historic Brownstone in Boston",
      description:
        "Step back in time in this elegant historic brownstone located in the heart of Boston.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1533619239233-6280475a633a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fHNreSUyMHZhY2F0aW9ufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 2200,
      location: "Boston",
      country: "United States",
      geometry: {
        type: "Point",
        coordinates: [-71.0589, 42.3601],
      },
      type: "Brownstone",
      bedrooms: 3,
      bathrooms: 2,
      guests: 5,
      checkin: "4:00 PM",
      features: ["Historic Charm", "WiFi", "Fireplace", "City View"],
      checkout: "12:00 PM",
    },
    {
      name: "Beachfront Bungalow in Bali",
      description:
        "Relax on the sandy shores of Bali in this beautiful beachfront bungalow with a private pool.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1602391833977-358a52198938?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzJ8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1800,
      location: "Bali",
      country: "Indonesia",
      geometry: {
        type: "Point",
        coordinates: [115.1889, -8.4095],
      },
      type: "Bungalow",
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      checkin: "2:00 PM",
      features: ["Private Pool", "Beachfront", "WiFi", "Breakfast Included"],
      checkout: "10:00 AM",
    },
    {
      name: "Mountain View Cabin in Banff",
      description:
        "Enjoy breathtaking mountain views from this cozy cabin in the Canadian Rockies.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTJ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 1500,
      location: "Banff",
      country: "Canada",
      geometry: {
        type: "Point",
        coordinates: [-115.5728, 51.1784],
      },
      type: "Cabin",
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      checkin: "3:30 PM",
      features: ["Mountain View", "Fireplace", "WiFi", "Deck"],
      checkout: "11:30 AM",
    },
    {
      name: "Art Deco Apartment in Miami",
      description:
        "Step into the glamour of the 1920s in this stylish Art Deco apartment in South Beach.",
      image: {
        filename: "listingimage",
        url: "https://plus.unsplash.com/premium_photo-1670963964797-942df1804579?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 1600,
      location: "Miami",
      country: "United States",
      geometry: {
        type: "Point",
        coordinates: [-80.1918, 25.7617],
      },
      type: "Apartment",
      bedrooms: 1,
      bathrooms: 1,
      guests: 2,
      checkin: "2:00 PM",
      features: ["WiFi", "Art Deco Decor", "Beach Access", "Balcony"],
      checkout: "10:00 AM",
    },
    {
      name: "Tropical Villa in Phuket",
      description:
        "Escape to a tropical paradise in this luxurious villa with a private infinity pool in Phuket.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1470165301023-58dab8118cc9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 3000,
      location: "Phuket",
      country: "Thailand",
      geometry: {
        type: "Point",
        coordinates: [98.3923, 7.8804],
      },
      type: "Villa",
      bedrooms: 3,
      bathrooms: 3,
      guests: 6,
      checkin: "3:00 PM",
      features: ["Infinity Pool", "WiFi", "Garden", "Ocean View"],
      checkout: "11:00 AM",
    },
    {
      name: "Historic Castle in Scotland",
      description:
        "Live like royalty in this historic castle in the Scottish Highlands. Explore the rugged beauty of the area.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1585543805890-6051f7829f98?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGJlYWNoJTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 4000,
      location: "Scottish Highlands",
      country: "United Kingdom",
      geometry: {
        type: "Point",
        coordinates: [-4.2026, 57.4907],
      },
      type: "Castle",
      bedrooms: 10,
      bathrooms: 8,
      guests: 20,
      checkin: "1:00 PM",
      features: ["Historic", "Fireplace", "Banquet Hall", "WiFi"],
      checkout: "10:30 AM",
    },
    {
      name: "Desert Oasis in Dubai",
      description:
        "Experience luxury in the middle of the desert in this opulent oasis in Dubai with a private pool.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1518684079-3c830dcef090?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZHViYWl8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 5000,
      location: "Dubai",
      country: "United Arab Emirates",
      geometry: {
        type: "Point",
        coordinates: [55.2708, 25.2048],
      },
      type: "Villa",
      bedrooms: 5,
      bathrooms: 5,
      guests: 10,
      checkin: "3:00 PM",
      features: ["Private Pool", "Desert View", "WiFi", "Chef"],
      checkout: "11:00 AM",
    },
    {
      name: "Rustic Log Cabin in Montana",
      description:
        "Unplug and unwind in this cozy log cabin surrounded by the natural beauty of Montana.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1586375300773-8384e3e4916f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 1100,
      location: "Montana",
      country: "United States",
      geometry: {
        type: "Point",
        coordinates: [-110.3626, 46.8797],
      },
      type: "Log Cabin",
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      checkin: "2:00 PM",
      features: ["Fireplace", "Mountain View", "WiFi", "Deck"],
      checkout: "10:00 AM",
    },
    {
      name: "Beachfront Villa in Greece",
      description:
        "Enjoy the crystal-clear waters of the Mediterranean in this beautiful beachfront villa on a Greek island.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 2500,
      location: "Mykonos",
      country: "Greece",
      geometry: {
        type: "Point",
        coordinates: [25.3289, 37.4467],
      },
      type: "Villa",
      bedrooms: 3,
      bathrooms: 3,
      guests: 7,
      checkin: "3:00 PM",
      features: ["Beachfront", "Pool", "WiFi", "Terrace"],
      checkout: "11:00 AM",
    },
    {
      name: "Eco-Friendly Treehouse Retreat",
      description:
        "Stay in an eco-friendly treehouse nestled in the forest. It's the perfect escape for nature lovers.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1488462237308-ecaa28b729d7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8c2t5JTIwdmFjYXRpb258ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 750,
      location: "Costa Rica",
      country: "Costa Rica",
      geometry: {
        type: "Point",
        coordinates: [-84.0907, 9.7489],
      },
      type: "Treehouse",
      bedrooms: 1,
      bathrooms: 1,
      guests: 2,
      checkin: "2:00 PM",
      features: ["Eco-Friendly", "Solar Power", "WiFi", "Forest View"],
      checkout: "10:00 AM",
    },
    {
      name: "Historic Cottage in Charleston",
      description:
        "Experience the charm of historic Charleston in this beautifully restored cottage with a private garden.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1587381420270-3e1a5b9e6904?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fGxvZGdlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 1600,
      location: "Charleston",
      country: "United States",
      geometry: {
        type: "Point",
        coordinates: [-79.9311, 32.7765],
      },
      type: "Cottage",
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      checkin: "3:00 PM",
      features: ["Private Garden", "WiFi", "Historic Decor", "Porch"],
      checkout: "11:00 AM",
    },
    {
      name: "Modern Apartment in Tokyo",
      description:
        "Explore the vibrant city of Tokyo from this modern and centrally located apartment.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1480796927426-f609979314bd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fHRva3lvfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      },
      price: 2000,
      location: "Tokyo",
      country: "Japan",
      geometry: {
        type: "Point",
        coordinates: [139.6917, 35.6895],
      },
      type: "Apartment",
      bedrooms: 1,
      bathrooms: 1,
      guests: 3,
      checkin: "4:00 PM",
      features: ["WiFi", "City View", "Air Conditioning", "Elevator"],
      checkout: "12:00 PM",
    },
    {
      name: "Lakefront Cabin in New Hampshire",
      description:
        "Spend your days by the lake in this cozy cabin in the scenic White Mountains of New Hampshire.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1578645510447-e20b4311e3ce?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NDF8fGNhbXBpbmd8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1200,
      location: "New Hampshire",
      country: "United States",
      geometry: {
        type: "Point",
        coordinates: [-71.5557, 43.1939],
      },
      type: "Cabin",
      bedrooms: 2,
      bathrooms: 1,
      guests: 4,
      checkin: "2:00 PM",
      features: ["Lakefront", "Kayaks", "Fireplace", "WiFi"],
      checkout: "10:00 AM",
    },
    {
      name: "Luxury Villa in the Maldives",
      description:
        "Indulge in luxury in this overwater villa in the Maldives with stunning views of the Indian Ocean.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8bGFrZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 6000,
      location: "Maldives",
      country: "Maldives",
      geometry: {
        type: "Point",
        coordinates: [73.2207, 3.2028],
      },
      type: "Villa",
      bedrooms: 2,
      bathrooms: 2,
      guests: 4,
      checkin: "12:00 PM",
      features: ["Overwater", "Private Pool", "WiFi", "Ocean View"],
      checkout: "10:30 AM",
    },
    {
      name: "Ski Chalet in Aspen",
      description:
        "Hit the slopes in style with this luxurious ski chalet in the world-famous Aspen ski resort.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGxha2V8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 4000,
      location: "Aspen",
      country: "United States",
      geometry: {
        type: "Point",
        coordinates: [-106.8374, 39.1911],
      },
      type: "Chalet",
      bedrooms: 5,
      bathrooms: 4,
      guests: 10,
      checkin: "3:00 PM",
      features: ["Ski-in/Ski-out", "Fireplace", "Hot Tub", "WiFi"],
      checkout: "11:00 AM",
    },
    {
      name: "Secluded Beach House in Costa Rica",
      description:
        "Escape to a secluded beach house on the Pacific coast of Costa Rica. Surf, relax, and unwind.",
      image: {
        filename: "listingimage",
        url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8YmVhY2glMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      },
      price: 1800,
      location: "Costa Rica",
      country: "Costa Rica",
      geometry: {
        type: "Point",
        coordinates: [-84.0907, 9.7489],
      },
      type: "Beach House",
      bedrooms: 3,
      bathrooms: 2,
      guests: 6,
      checkin: "2:00 PM",
      features: ["Beachfront", "Surfboards", "WiFi", "Hammock"],
      checkout: "10:00 AM",
    },
  ];
  
  module.exports = { data: sampleListings };